# Generated by Django 4.2.1 on 2023-05-11 15:28

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postmodel',
            managers=[
                ('list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, unique_for_date='publish', unique_for_month='publish', unique_for_year='publish'),
        ),
    ]
