# Generated by Django 4.2.1 on 2023-05-11 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postmodel_managers_alter_postmodel_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, unique_for_date='publish'),
        ),
    ]
