# Generated by Django 4.2.1 on 2023-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel_tags'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postmodel',
            managers=[
            ],
        ),
    ]
